### ISSUE TITLE
1차 기능 기획

### ISSUE THREAD

**Issue by YehyeokBang** [WASSUP-Project/WASSUP-Web#2]
### 할 일
- [x] 핵심 기능 기획 및 정리
- [x] 해보고 싶은 기능 및 기술 정리
- [x] 작업 컨벤션 작성

### 내용
- 디자인 작업은 팀 피그마로 진행합니다.
- 사용하려는(또는 하고픈) 기술 등을 확인합니다.

**Comment by YehyeokBang** [comment]
### 학원에서 사용할 수 있는 출결 확인 서비스
- 원장, 원생, 학부모가 주요 대상입니다.
- 원장은 원생들의 정보를 관리할 수 있습니다.
- 데스크에서 서비스를 사용하여 출결을 관리합니다.
- 학부모에게 자녀 등하원 안내 메시지가 전송됩니다.
- 학부모에게 통지서 같은 공지사항을 전송할 수 있습니다.

### 참고 서비스
- [출결버스](https://www.checkbus.co.kr/homepage/?rel=)
- [랠리즈](https://www.rallyz.co.kr/introduce/attendance)
- [아이앰클래스 (아이앰스쿨, 아이앰티처 등 존재)](https://class.iamservice.net/intro/academy)

**Comment by dd-jiyun** [comment]
## 사용해보고 싶은 기능

- Discord logback 이용해서 배포 서버 로그에서 ERROR를 알려주는 기능
- 원생의 출결 상황을 문자메세지로 전송 기능
- 사업자 번호를 받아오면 OpenAPI 사용해서 확인하는 기능


## 참고
- [Logback](https://velog.io/@qwe916/Discord%EB%A1%9C-Spring-Logback-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0)
- [SMS 전송](https://velog.io/@aloha006/spring-%EB%AC%B8%EC%9E%90-API-%EC%82%AC%EC%9A%A9)

**Comment by YehyeokBang** [comment]
### 작업 컨벤션
- 초키 세팅 이후에 작업은 브랜치를 추가하여 진행하고 PR 혹은 Merge를 사용합니다.
- 작업 단위로 이슈를 생성합니다. (새로운 기능 추가, 버그 수정 등)
- 커밋 메시지는 [#이슈번호] feat: 작업 내용 형태로 작성합니다. 예시는 아래와 같습니다.
```cmd
// 새로운 기능 추가
[#2] feat: 로그인 기능 구현

// 버그 수정
[#5] fix: 아이디 공백이 허용되던 문제 수정

// 간단한 내용은 이슈 번호가 없어도 됩니다.
fix: 오타 수정
```

커밋 메시지의 키워드
- `feat` : 새로운 기능 구현
- `refactor` : 기능 추가 없이 개선 및 수정
- `fix` : 오류 수정
- `docs` : 문서 관련
- `style` : 디자인 개선

브랜치명 컨벤션
- `feat/login` 처럼 키워드/간단한작업소개 형태로 작성합니다. 예시는 아래와 같습니다.
```cmd
// 푸시알림 구현 작업 브랜치
feat/push-notification

// 이미지 업로드 성능 개선 작업 브랜치
refactor/upload-image-perf
```

**Comment by YehyeokBang** [comment]
### 질문
- 학원(그룹)장이 모든 것을 관리할 수 있도록 하는 것이 좋을까요? 아니면 학부모도 가입을 통해 서비스를 이용할 수 있는 것이 좋을까요?

**Comment by YehyeokBang** [comment]
### 오프라인 회의 요약

![Image](https://github.com/WASSUP-Project/WASSUP-Web/assets/107793780/6632b0fd-3803-44b7-983b-11cbcdaf149e)
