### ISSUE TITLE
내 그룹 페이지 기능 구현

### ISSUE THREAD

**Issue by YehyeokBang** [WASSUP-Project/WASSUP-Web#44]
### 할 일
- [x] 로그인한 관리자의 그룹 보여주기 기능 구현
- [x] 그룹 생성 기능 구현

### 내용
-  로그인한 관리자가 소유한 그룹을 보여주는 페이지 API 연결 작업을 진행합니다.

### 결과

https://github.com/WASSUP-Project/WASSUP-Web/assets/107793780/9cfd64ba-f217-40c3-8d4f-6d3af53b5a70

**Comment by YehyeokBang** [comment]
### 요청 @dd-jiyun 
<img width="901" alt="image" src="https://github.com/WASSUP-Project/WASSUP-Web/assets/107793780/95f5026a-7a49-4470-aaa3-7160cb0fc254">

해당 화면에 사용할 관리자가 소유한 그룹 정보들을 확인할 수 있는 API가 필요합니다!

**Comment by dd-jiyun** [comment]
네 확인했습니다!

**Comment by YehyeokBang** [comment]
맴버 가입 대기 여부가 필요하기 때문에 작업 완료 후 진행하겠습니다.

**Comment by YehyeokBang** [comment]
배포된 API 사용하여 작업 완료했습니다!
