### ISSUE TITLE
그룹 인원 추가 관련 페이지 화면 구현

### ISSUE THREAD

**Issue by YehyeokBang** [WASSUP-Project/WASSUP-Web#51]
### 할 일
- [x] 관리자가 사용할 멤버 가입 메시지 전송 페이지 화면 구현
- [x] 학부모가 학원 가입을 위한 자녀 정보 작성 페이지 화면 구현
- [x] 관리자가 가입 대기 중인 멤버 관리를 위한 페이지 화면 구현

### 내용
- 멤버로 가입하기 위해서는 관리자가 학부모의 전화번호를 받아서 `가입 메시지`를 전송합니다.
- `가입 메시지`에는 그룹 가입을 위한 `학원 고유 코드`와 `정보 작성 홈페이지 url`이 포함되어 있습니다.
- 학부모는 정보 작성 홈페이지로 들어가 가입하려는 자녀의 개인 정보와 학원 고유 코드를 입력하고 가입 신청을 합니다.
- 관리자는 가입 신청 목록(대기 중인 멤버)을 보고 수락하거나 거절할 수 있습니다.

### 결과

https://github.com/WASSUP-Project/WASSUP-Web/assets/107793780/a302cec8-2f52-406d-83d8-1c20d6abf10b

- 전체적으로 그룹 관리 페이지에 사용하는 색상을 통일감있게 수정했습니다.
- 가입된 멤버와 가입 대기 중인 멤버를 분리하여 보여줍니다.
- 전화번호를 통해 가입 절차를 안내받은 후 가입 신청을 할 수 있습니다. 이후 관리자의 승인 후 가입이 완료됩니다.

**Comment by YehyeokBang** [comment]
@dd-jiyun 다시 한 번 읽어보고 피드백 부탁드려요!

**Comment by dd-jiyun** [comment]
모든 멤버, 가입 신청한 멤버, 가입된 멤버 이렇게 세 개로 분류되는 건가요? 
그런데 해당 그룹의 모든 멤버는 어디에 사용할 예정이신가요!?

**Comment by YehyeokBang** [comment]
> 모든 멤버, 가입 신청한 멤버, 가입된 멤버 이렇게 세 개로 분류되는 건가요? 그런데 해당 그룹의 모든 멤버는 어디에 사용할 예정이신가요!?

현재 어디에 사용하지는 않고 유동적인 API를 만들면 좋을 것 같아서 말씀드렸어요! 어떤 상태의 인원 목록을 전달할 때마다 만들면 uri가 복잡해질 것 같아서요!

**Comment by YehyeokBang** [comment]
만들다보니 그룹 관리 페이지들의 색상이 통일되지 않아서 지저분한 느낌이 있는 것 같아서 통일감있게 수정하려고 합니다.

**Comment by dd-jiyun** [comment]
좋습니당!

**Comment by YehyeokBang** [comment]
<img width="938" alt="image" src="https://github.com/WASSUP-Project/WASSUP-Web/assets/107793780/df3b66ba-759e-410d-af38-3550ba1441c5">

학부모가 받게 되는 그룹 가입 신청을 위한 페이지는 다음과 같습니다!
