### ISSUE TITLE
원활한 화면 확인을 위한 초기 더미 데이터 요청

### ISSUE THREAD

**Issue by YehyeokBang** [WASSUP-Project/WASSUP-Web#55]
### 상황 설명
- 회원가입 및 로그인 기능은 동작하지만, 휴대폰 인증 관련 Web 발신 메시지 크레딧이 부족하기 때문에 배포 후 테스트가 불편해요
- 백엔드를 배포할 때 완전관리형 서버리스 `Cloud Run`을 사용했기 때문에 일정 기간 사용하지 않을 때는 컴퓨터 리소스를 사용하지 않습니다. 이로 인해 콜드 스타트를 경험하게 될 수 있습니다. 또한 현재 개발 단계라서 JPA의 `ddl-auto` 옵션을 `create`로 사용하고 있어서 일정기간 리소스를 사용하지 않다가 API 요청을 보내면 데이터베이스가 새롭게 만들어지면서 기존 데이터가 없어지는 불편함이 발생해요.

### 요청 @dd-jiyun 
- 더미 데이터(관리자, 그룹 등)를 만들어서 스프링 부트 앱이 다시 켜질 때(ddl-auto: create), 이 더미 데이터가 들어가게끔 초기화 해주면 좋을 것 같아요.

**Comment by dd-jiyun** [comment]
네 !! 수정하겠습니다 👍

**Comment by YehyeokBang** [comment]
추가된 것 확인했습니다! 감사합니다!
