### ISSUE TITLE
출결 관리 기능 회의

### ISSUE THREAD

**Issue by YehyeokBang** [WASSUP-Project/WASSUP-Web#56]
### 할 일
- [x] 출결 관리 기능 회의

### 내용
- 출결 관리 기능을 구현하기 전 회의를 다시 한 번 진행하여 부족한 부분이나 놓친 부분은 없는지 다시 한 번 점검합니다.
- 구현 전 테이블 구조, 디자인, 사용성을 평가합니다.
- @dd-jiyun

**Comment by YehyeokBang** [comment]
## 출석 방식
- 아이패드나 노트북을 안내 데스크에 두고 원생들이 출석 체크를 하는 방식을 염두하고 진행했어요.

---

1. 관리자로 로그인해서 그룹 관리 페이지에서 원생들이 직접 번호를 누르는 방식으로 출석할 수 있는 화면으로 이동하여 출석을 받도록 한다.
-> 출근하여 아이들이 오기 전 관리자 로그인 후 출결관리 탭으로 들어가 출석 버튼을 눌러 원생들이 출석을 누를 수 있게 하기

- 장점 : 구현이 아래 방식보다는 간단할 수 있어요.
- 단점 : 원생들이 페이지를 이동하여 관리자 페이지로 이동할 수 있어요.

---

2. 출석을 하기 위해 관리자는 링크를 발급받아 아이패드나 노트북을 활용해 출석을 받도록 한다.
-> 출근하여 아이들이 오기 전 출석화면으로 이동할 수 있는 링크를 발급받고 다른 디바이스로 접속하여 원생들이 출석을 누를 수 있게 하기

- 장점 : 장비나 페이지 이동에 대한 걱정이 줄어들어요.
- 단점 : 비교적 구현이 어려울 수 있어요.

---

일단 저는 아래의 방식을 채택하는 것이 추후에도 좋을 것 같아요. 그룹이 여러 개 있다보니 관리자 화면과 출석 화면이 분리되어 있으면 더 유용할 것 같아요.

**Comment by dd-jiyun** [comment]
### 출결 기능 관련 1차 회의
위의 작성된 내용으로 회의 한 결과 2번 방식을 선택하였습니다.

### 출결 기능 흐름
1. 관리자가 출석을 하기 위해 고유 링크를 발급 받습니다.
    - 고유 링크에는 파라미터로 중복되지 않는 고유 값이 포함되어 있습니다.
2. 발급 받음과 동시에 서버에 고유 값과 고유 링크를 발급 받은 그룹의 id 값이 캐시에 저장됩니다.
3. 고유 링크로 접속하면 출석할 수 있는 화면이 나타납니다.
4. 해당 화면에서 출석할 인원의 전화번호 끝 4자리를 입력 받습니다.
5. 고유 링크의 파라미터인 고유 값과 전화번호 끝 4자리를 서버에 전송합니다.
6. 서버에선 고유 값으로 캐시에 저장된 그룹 id를 사용하고, 전화번호 끝 4자리를 통해 출석할 인원을 찾습니다.
7. 만약 중복되는 인원이 있다면, 중복된 인원 중 누구인지 확인하는 과정을 거칩니다. (응답으로 중복되는 인원의 이름 목록을 제공하여 선택하여 출석할 수 있도록 합니다.)
