### ISSUE TITLE
출결 기능 관련 회의

### ISSUE THREAD

**Issue by YehyeokBang** [WASSUP-Project/WASSUP-Web#87]
### 할 일
- [x] 출결 기능 관련 회의 진행

### 내용
- 등하원 기능, 출결 통계 등 기능 회의를 진행합니다.

**Comment by YehyeokBang** [comment]
등원(출석)은 완료했고 하원 기능은 화면이나 API 구성에 대해 어떻게 할지 고민해봐야 할 것 같습니다!
추가적으로 출결 관리 기능이 부족한 것 같아요. 직접 출결을 지정할 수 있다거나, 통계 자료 등 보완하면 좋을 것 같아요!

**Comment by dd-jiyun** [comment]
네 ! 관리자 페이지에서 출결 관리를 할 수 있으면 좋겠네요 
기능 구상 해보겠습니다

**Comment by dd-jiyun** [comment]
### 특정 날짜 별 그룹 상태 관리
출석 링크를 생성하게 되면 금일 학원이 오픈된 상태임을 표시하게 됩니다.

### 등하원 직접 수정
관리자가 그룹에 속한 원생의 출결을 직접 수정할 수 있습니다.

### 참고
![Frame 55](https://github.com/WASSUP-Project/WASSUP-Web/assets/84395062/16d1c2ee-a53c-4f55-86c1-5f15e50085bf)

<img width="470" alt="등하원관리 ui" src="https://github.com/WASSUP-Project/WASSUP-Web/assets/84395062/679b75e0-829a-4fc0-8e64-e999a5f59bb7">

**Comment by YehyeokBang** [comment]
좋아요!! 출석체크를 할지 말지(오늘 그룹이 영업을 하는지)를 알 수 있으면 나중에 분석 자료를 제공할 때도 유용할 것 같아요!
특정 인원의 출결을 수정할 수 있는 기능도 좋아요!

**Comment by sinamong0620** [comment]
귀엽네
