### ISSUE TITLE
등하원 직접 수정 기능 구현

### ISSUE THREAD

**Issue by YehyeokBang** [WASSUP-Project/WASSUP-Web#94]
### 할 일
- [x] 등하원 직접 수정 기능 구현

### 내용
- #92 에서 구현한 화면에 맞게 출석, 결석 등을 관리자가 직접 수정할 수 있는 기능을 구현합니다.

### 결과

https://github.com/WASSUP-Project/WASSUP-Web/assets/107793780/69943aae-e565-4ee3-9baa-5e032c7dc6a0

**Comment by YehyeokBang** [comment]
@dd-jiyun 
하원 처리되면 출석률에 반영이 안되는 것 같아요 확인 부탁드려요! @dd-jiyun 
ex) 하원은 출석 이후에 일어날 수 있는 일이기 때문에 3명 중 1명이 출석하고 1명이 하원한 상태라면 66%의 출석률이 기대되지만 33%으로 나오네요.

**Comment by dd-jiyun** [comment]
네 확인하고 수정하겠습니다!
